import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/navbar";

export const metadata: Metadata = {
  title: "next-ts-movie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#1e1e20] w-screen h-full min-h-screen overflow-x-hidden text-white">
        <div className="w-full h-full">
          <Navbar />
        </div>
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
